fix(gb): failing to delete some git branches
Because they're not fully merged:

```
error: The branch 'foo' is not fully merged.
If you are sure you want to delete it, run 'git branch -D foo'.
```